version: '3'

services:
  worker:
    build: worker
    ports:
      - "2226-2300:22"
    command: "/bin/bash service ssh start "
    command: "/usr/sbin/sshd -D"

networks:
  default:
    external:
      name: net