version: '3'

services:
    jenkins_master:
        image: jenkins
        ports:
            - "80:8080"
        depends_on:
            - hawthorn_worker
    hawthorn_worker:
        image: jenkins_worker:hawthorn.master
        ports:
            - "2226-2300:22"

networks:
    default:
        external:
            name: net
