---
# The Git Plugin provides the following options
# Global Config user.name Value: if provided git config user.name <value> is called before builds. This can be overridden by individual projects.
# Global Config user.email Value: if provided git config user.email <value> is called before builds. This can be overridden by individual projects.
# Create new accounts base on author/committer's email: if checked, upon parsing of git change logs, new user accounts are created on demand for the identified committers / authors in the internal Jenkins database. The e-mail address is used as the id of the account.

NAME: 'username'
EMAIL: 'user@email.com'
