---
- CREDENTIAL_ID: 'secretText1' #GitHub OAuth token
  MANAGE_HOOKS: true
  USE_CUSTOM_API_URL: 'true' # turn to false, if you dont use custom API_URL
  API_URL: 'www.example.com/api'
  CACHE_SIZE: 30
