---
- host: "hawthorn_worker_1"
  label: "hawthorn-jenkins-worker jenkins-worker flow-worker-bokchoy flow-worker-lettuce flow-worker-quality flow-worker-python"
  executors: "1"
  home: "/home/jenkins"
  credential: "jenkins-worker"
- host: "hawthorn_worker_2"
  label: "hawthorn-jenkins-worker jenkins-worker flow-worker-bokchoy flow-worker-lettuce flow-worker-quality flow-worker-python"
  executors: "1"
  home: "/home/jenkins"
  credential: "jenkins-worker"
- host: "hawthorn_worker_3"
  label: "hawthorn-jenkins-worker jenkins-worker flow-worker-bokchoy flow-worker-lettuce flow-worker-quality flow-worker-python"
  executors: "1"
  home: "/home/jenkins"
  credential: "jenkins-worker"
