---
- host: "hawthorn_worker_1"
  label: "hawthorn-jenkins-worker jenkins-worker"
  executors: "1"
  home: "/var/lib/jenkins"
  credential: "jenkins-worker"
- host: "hawthorn_worker_2"
  label: "hawthorn-jenkins-worker jenkins-worker"
  executors: "1"
  home: "/var/lib/jenkins"
  credential: "jenkins-worker"
- host: "hawthorn_worker_3"
  label: "hawthorn-jenkins-worker jenkins-worker"
  executors: "1"
  home: "/var/lib/jenkins"
  credential: "jenkins-worker"
